name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Create Deployment Package
        run: tar --exclude='./node_modules' --exclude='./app.tar' -czf app.tar .

      - name: Check if app.tar Exists
        run: ls -la

      - name: Create Private Key File
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Deploy to AWS EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no app.tar ubuntu@ec2-3-110-56-31.ap-south-1.compute.amazonaws.com:~
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-3-110-56-31.ap-south-1.compute.amazonaws.com "tar -xzf /home/ubuntu/app.tar -C /home/ubuntu/NodeJS_APP/ && cd /home/ubuntu/NodeJS_APP/ && node app.js > /dev/null 2>&1 &"

      - name: Cleanup Private Key
        run: rm -f private_key.pem
