name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}

      - name: Build artifacts
        run: |
          tar -czf app.tar node_modules package-lock.json
        working-directory: ${{ github.workspace }}
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}  # Store your key in GitHub Secrets

      - name: Deploy to AWS EC2
        run: |
          chmod 400 $AWS_PRIVATE_KEY
          scp -i $AWS_PRIVATE_KEY -o StrictHostKeyChecking=no app.tar ubuntu@ec2-3-110-56-31.ap-south-1.compute.amazonaws.com:~
          ssh -i $AWS_PRIVATE_KEY -o StrictHostKeyChecking=no ubuntu@ec2-3-110-56-31.ap-south-1.compute.amazonaws.com "tar -xzf /home/ubuntu/app.tar -C /home/ubuntu/NodeJS_APP/ && cd /home/ubuntu/NodeJS_APP/ && node app.js > /dev/null 2>&1 &"
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

